export interface ACSIndustry {
  slug: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  longDescription: string;
  icon: string;
  heroImage: string;
  relevantServices: string[]; // service slugs
  keyChallenges: string[];
  acsSolutions: string[];
  complianceRequirements: string[];
  caseStudy: {
    title: string;
    clientType: string;
    challenge: string;
    solution: string;
    result: string;
  };
  keywords: string[];
}

export const ACS_INDUSTRIES: ACSIndustry[] = [
  {
    slug: 'construction',
    name: 'Construction Sites & Infrastructure Projects',
    shortName: 'Construction Security',
    tagline: 'Perimeter protection, material shrinkage prevention, and 24x7 heavy asset watch.',
    description: 'Specialized construction security services, perimeter access control, material theft prevention, and contractor gate pass management.',
    longDescription: 'ACS delivers battle-tested security solutions for high-risk construction sites, highway infrastructure projects, and mega commercial developments. Our personnel control material shrinkage, enforce strict entry/exit gate passes, verify contractor labour rosters, and safeguard expensive machinery, copper cabling, and raw materials from organized pilferage.',
    icon: '🏗️',
    heroImage: '/images/guarding.jpg',
    relevantServices: ['security-guard', 'industrial-security', 'night-patrol', 'surveillance-cctv', 'fire-fighting'],
    keyChallenges: [
      'High-value raw material shrinkage (steel, copper wiring, cement, diesel)',
      'Unvetted sub-contractor labour entering restricted hazardous work zones',
      'Massive open perimeters vulnerable to after-hours trespassing',
      'Severe fire hazards from hot works, welding, and fuel storage depots',
    ],
    acsSolutions: [
      'Digital material in/out logging with mandatory weighbridge cross-verification',
      'Perimeter patrol units equipped with searchlights and GPS patrol wands',
      'Biometric and photo contractor labour pass management at turnstiles',
      'Trained first-responder fire wardens and NBC-compliant emergency protocols',
    ],
    complianceRequirements: [
      'The Building and Other Construction Workers (BOCW) Act 1996 compliance',
      'Contract Labour (Regulation & Abolition) Act 1970 licensing',
      'Mandatory PPE compliance (helmets, high-vis vests, steel-toe boots)',
      'Statutory Minimum Wages, EPF & ESIC documentation',
    ],
    caseStudy: {
      title: 'Zero Material Shrinkage on 40-Acre Commercial SEZ Project',
      clientType: 'National Tier-1 Infrastructure EPC Contractor',
      challenge: 'The client experienced recurring nighttime copper cabling theft and inventory discrepancies exceeding ₹14 Lakhs per quarter.',
      solution: 'ACS deployed a 24-guard tactical team with canine patrol along the perimeter, computerized gate pass barcode scanners, and surprise night supervisor audits.',
      result: '100% reduction in unauthorized material loss over 18 months, with zero safety non-compliance penalties.',
    },
    keywords: [
      'construction security services India',
      'construction site security guards',
      'infrastructure project security agency',
      'builder site guard deployment',
      'building site theft prevention guards',
    ],
  },
  {
    slug: 'hotels',
    name: 'Hotels, Resorts & Hospitality Establishments',
    shortName: 'Hotel Security',
    tagline: 'Discreet luxury guest protection, baggage screening, and banquet crowd control.',
    description: 'Five-star hospitality security, front-of-house greeting guards, baggage scanning, VIP escort, and crisis de-escalation.',
    longDescription: 'Hospitality demands an uncompromising balance between warmth and ironclad vigilance. ACS provides groom-trained, bilingual security officers for luxury hotels, boutique resorts, and event banquet halls. Our personnel handle guest greeting, under-vehicle scanning, valet perimeter watch, keycard elevator control, and discreet dispute de-escalation without disrupting the guest experience.',
    icon: '🏨',
    heroImage: '/images/specialevent.jpg',
    relevantServices: ['security-guard', 'surveillance-cctv', 'event-security', 'executive-protection', 'housekeeping'],
    keyChallenges: [
      'Balancing welcoming guest hospitality with stringent physical access control',
      'Large banqueting crowds, uninvited party crashers, and celebrity crowd management',
      'Parking congestion, VIP vehicle protection, and valet liability disputes',
      'Late-night intoxicated guest disturbances requiring discreet de-escalation',
    ],
    acsSolutions: [
      'Well-groomed, etiquette-trained hospitality security guards and concierges',
      'Under-vehicle surveillance mirrors (UVSM) and DFMD/HHMD baggage screening',
      'Discreet female security officers for family suites and female guest safety',
      'Direct coordination with local police for VIP and celebrity banqueting events',
    ],
    complianceRequirements: [
      'State Tourism & Police Hotel Security Clearance guidelines',
      'PSARA licensed armed and unarmed security guards',
      'Mandatory fire safety and guest evacuation mock drills',
      'Food & hospitality sanitation compliance coordination',
    ],
    caseStudy: {
      title: 'VIP Summit & International Diplomatic Delegation Hosting',
      clientType: '5-Star Luxury Heritage Hotel in Kolkata',
      challenge: 'Hosting 40+ international trade delegates with simultaneous high-volume public banqueting events across two ballrooms.',
      solution: 'ACS deployed 35 executive security guards, 4 PSOs, handheld metal detector checkpoints, and dedicated perimeter vehicle cordoning.',
      result: 'Seamless 4-day summit concluded with zero security breaches and formal commendation from hotel general management.',
    },
    keywords: [
      'hotel security services India',
      'hospitality security guards',
      'luxury resort security agency',
      'banquet security guards',
      'hotel guest protection and bouncers',
    ],
  },
  {
    slug: 'warehouses',
    name: 'Warehouses, Logistics & Supply Chain Hubs',
    shortName: 'Warehouse Security',
    tagline: 'Dock bay surveillance, inward/outward inventory verification, and 24x7 gate security.',
    description: 'Comprehensive warehouse security, logistics yard patrolling, seal verification, inventory shrinkage control, and CCTV monitoring.',
    longDescription: 'Modern e-commerce and logistics fulfillment centers operate 24x7 with continuous movement of trucks, pallets, and high-value merchandise. ACS deploys specialized logistics security guards trained in truck seal verification, computerized gate register entries, driver identity vetting, dock door monitoring, and frisking protocols that eliminate inventory shrinkage.',
    icon: '📦',
    heroImage: '/images/guarding.jpg',
    relevantServices: ['industrial-security', 'security-guard', 'night-patrol', 'surveillance-cctv', 'fire-fighting'],
    keyChallenges: [
      'Internal inventory shrinkage during packing, picking, and dock transfer',
      'Unauthorized vehicle entry and driver collusion at loading bays',
      'High fire risk due to stacked packaging, cardboard, and battery charging zones',
      'Perimeter vulnerability across sprawling 100,000+ sq ft logistics parks',
    ],
    acsSolutions: [
      'Rigorous physical frisking and metal-detector scans for warehouse staff on exit',
      'Truck seal verification, invoice cross-matching, and digital gate pass software',
      'High-definition CCTV control room operators tracking dock loading bays',
      'Trained fire fighting squads with continuous sprinkler and extinguisher upkeep',
    ],
    complianceRequirements: [
      'Warehousing (Development and Regulation) Act compliance support',
      'Factories Act 1948 or State Shops & Establishment Act compliance',
      'Contract Labour (R&A) Act 1970 registration',
      'Central & State Sphere statutory minimum wages with full EPF/ESIC',
    ],
    caseStudy: {
      title: 'Pilferage Elimination in 120,000 Sq Ft FMCG Logistics Depot',
      clientType: 'National Logistics & Supply Chain Operator',
      challenge: 'The facility reported continuous petty theft and misplacement of consumer electronics and cosmetics averaging ₹8 Lakhs monthly.',
      solution: 'ACS overhauled entry/exit gates, introduced double-blind container seal inspections, and deployed female and male search staff at all shift turnarounds.',
      result: 'Inventory shrinkage dropped to 0.01% within the first 60 days of ACS takeover.',
    },
    keywords: [
      'warehouse security services India',
      'logistics park security agency',
      'godown security guards',
      'supply chain security management',
      'dock bay security and cargo verification',
    ],
  },
  {
    slug: 'residential',
    name: 'Residential Societies & Gated Communities',
    shortName: 'Residential Security',
    tagline: 'Smart visitor logging, boom barrier operation, night rounds, and family safety.',
    description: 'Professional residential security guards, apartment society gate management, boom barrier control, visitor apps, and night patrolling.',
    longDescription: 'Residential gated communities require trustworthy, polite, and alert security guards who safeguard families, children, and elderly residents. ACS supplies verified security guards and supervisors for high-rise apartment complexes, townships, and villas. Our teams operate digital visitor management systems, enforce vehicle speed limits, conduct hourly night clocking rounds, and manage emergency situations swiftly.',
    icon: '🏡',
    heroImage: '/images/training.jpg',
    relevantServices: ['security-guard', 'night-patrol', 'surveillance-cctv', 'housekeeping', 'pest-control'],
    keyChallenges: [
      'Unscreened delivery personnel, courier executives, and domestic staff entries',
      'Unauthorized parking disputes and traffic blockages inside society lanes',
      'Vulnerability of ground-floor residences, basements, and clubhouse amenities at night',
      'Immediate crisis management during medical emergencies or lift breakdowns',
    ],
    acsSolutions: [
      'Digital visitor verification (MyGate / NoBrokerHood integration support)',
      'Boom barrier operations, resident RFID verification, and guest parking guidance',
      'Hourly night guard patrol rounds with RFID checkpoint tags along society walls',
      'First-aid and CPR trained security supervisors available 24x7 on site',
    ],
    complianceRequirements: [
      '100% Police Character Verification on all deployed residential guards',
      'State PSARA controlling authority compliance',
      'Adherence to State Apartment Ownership Act security regulations',
      'Statutory minimum wage, bonus, and EPF/ESIC compliance for all staff',
    ],
    caseStudy: {
      title: 'Integrated Gate Security for 850-Apartment High-Rise Township',
      clientType: 'Resident Welfare Association (RWA)',
      challenge: 'Previous agency suffered from high guard absenteeism, frequent sleeping-on-duty complaints, and unrecorded delivery agent entries.',
      solution: 'ACS deployed 28 trained guards, 2 dedicated head supervisors, digital patrol monitoring wands, and biometric clock-in systems.',
      result: 'Zero guard absenteeism, 100% visitor vehicle logging, and over 98% resident satisfaction score in annual RWA audit.',
    },
    keywords: [
      'residential security services India',
      'apartment security guards',
      'gated community security agency',
      'society security guard services',
      'RWA security contractor',
    ],
  },
  {
    slug: 'corporate',
    name: 'Corporate Offices, IT Parks & BFSI',
    shortName: 'Corporate Security',
    tagline: 'Lobby reception security, employee badge access control, and executive safety.',
    description: 'Corporate security solutions, access control provisioning, executive floor protection, lobby reception, and server room safety.',
    longDescription: 'ACS provides corporate security personnel tailored for Fortune 500 offices, tech parks, BFSI institutions, and consulting firms. Our corporate security guards project a sharp, professional image, handle visitor pass creation, monitor turnstiles, safeguard critical server rooms, and ensure full compliance with global enterprise security standards.',
    icon: '🏢',
    heroImage: '/images/guarding.jpg',
    relevantServices: ['security-guard', 'surveillance-cctv', 'executive-protection', 'fire-fighting', 'housekeeping'],
    keyChallenges: [
      'Unauthorized physical access to data centers, server rooms, and executive suites',
      'Tailgating at speed gates and turnstiles during peak morning and evening rushes',
      'Handling disgruntled ex-employees or hostile external visitors professionally',
      'Ensuring fire evacuation compliance across multi-storey glass facade towers',
    ],
    acsSolutions: [
      'Bilingual, smart-uniformed front desk corporate security guards',
      'Access control badge integration, visitor pass management, and bag x-ray checks',
      'Ex-defence security officers leading building safety and evacuation plans',
      '24x7 BMS / CCTV control room monitoring with incident escalation protocols',
    ],
    complianceRequirements: [
      'ISO 27001 physical security adherence support',
      'National Building Code (NBC) 2016 Fire & Life Safety norms',
      'Shops and Commercial Establishments Act compliance',
      'Statutory EPF, ESIC, and Minimum Wages Act documentation',
    ],
    caseStudy: {
      title: 'Consolidated Security for 500,000 Sq Ft Tech Park Campus',
      clientType: 'Global IT Services Provider',
      challenge: 'The campus required 60+ guards across 3 interconnected towers with strict zero-tailgating protocols and NDA compliance.',
      solution: 'ACS deployed a corporate security cadre with specialized access-gate training, biometric turnaround controls, and daily supervisor audits.',
      result: 'Passed 4 consecutive third-party ISO and global client physical security audits with zero non-conformities.',
    },
    keywords: [
      'corporate security services India',
      'office security guard agency',
      'IT park security management',
      'commercial building security services',
      'BFSI bank office security guards',
    ],
  },
  {
    slug: 'hospitals',
    name: 'Hospitals & Healthcare Institutions',
    shortName: 'Hospital Security',
    tagline: 'Emergency triage de-escalation, ICU access control, and doctor safety.',
    description: 'Specialized healthcare security, patient crowd management, emergency ward de-escalation, ICU access restriction, and hospital facility care.',
    longDescription: 'Hospitals are high-stress environments where physical security must safeguard doctors, nursing personnel, and vulnerable patients without impeding critical medical care. ACS provides trained healthcare security guards equipped for emergency room crowd de-escalation, newborn ward protection, oxygen plant surveillance, and ambulance bay clearance.',
    icon: '🏥',
    heroImage: '/images/investigation.jpg',
    relevantServices: ['security-guard', 'housekeeping', 'janitorial', 'pest-control', 'surveillance-cctv'],
    keyChallenges: [
      'Aggressive mobs and relatives threatening medical staff during patient emergencies',
      'Overcrowded outpatient departments (OPD) and blocked emergency ambulance bays',
      'Risk of infant abduction or unauthorized entry into maternity and pediatric wards',
      'Strict bio-medical waste segregation and infection control compliance',
    ],
    acsSolutions: [
      'Trained de-escalation security teams stationed at Emergency / Triage desks',
      'Biometric / smart badge checkpoints for ICUs, neonatal units, and surgical suites',
      'Dedicated traffic marshals maintaining clear, unhindered ambulance corridors',
      'NABH-compliant security SOPs, emergency panic button monitoring, and mock drills',
    ],
    complianceRequirements: [
      'National Accreditation Board for Hospitals & Healthcare Providers (NABH) safety norms',
      'Clinical Establishments (Registration and Regulation) Act guidelines',
      'State-specific Medicare Service Persons and Medicare Service Institutions Protection Acts',
      'Statutory minimum wages and 100% EPF/ESIC compliance for all deployed personnel',
    ],
    caseStudy: {
      title: 'Zero Violence Incidents in 650-Bed Multispecialty Hospital',
      clientType: 'Leading Tertiary Care Hospital Network',
      challenge: 'Recurring friction between agitated patient relatives and emergency room doctors leading to operational disruptions.',
      solution: 'ACS deployed 48 specialized hospital guards trained in verbal de-escalation, established a 2-tier triage security cordon, and installed quick-reaction alarm points.',
      result: 'Achieved zero violent incidents and 100% compliance with NABH physical security parameters over 24 months.',
    },
    keywords: [
      'hospital security services India',
      'healthcare security agency',
      'hospital guard deployment',
      'emergency ward security guards',
      'NABH compliant hospital security',
    ],
  },
  {
    slug: 'industrial-zones',
    name: 'Industrial Plants, Manufacturing & SEZs',
    shortName: 'Industrial Security',
    tagline: 'Perimeter protection, hazmat safety, union dispute management, and gate control.',
    description: 'Heavy industrial security, plant perimeter surveillance, material gate passes, hazardous zone access control, and fire safety squads.',
    longDescription: 'ACS provides heavy-duty industrial security for steel mills, automotive manufacturing plants, chemical refineries, and Special Economic Zones (SEZs). Our guards are trained in hazardous material awareness, union strike picket mitigation, shift turnaround crowd flow, and rigorous vehicle inspection.',
    icon: '🏭',
    heroImage: '/images/guarding.jpg',
    relevantServices: ['industrial-security', 'fire-fighting', 'night-patrol', 'surveillance-cctv', 'manpower-outsourcing'],
    keyChallenges: [
      'Theft of raw materials, metal ingots, machinery components, and fuel',
      'Labour unrest, unauthorized union picketing, and gate blockades',
      'Severe industrial fire hazards and toxic chemical exposure risks',
      'Large volumes of contract workers during scheduled plant turnaround and maintenance',
    ],
    acsSolutions: [
      'Ex-servicemen led industrial security teams with strict command hierarchy',
      'Automated weighbridge logging and truck undercarriage mirror inspections',
      'Dedicated industrial fire fighting squads and HAZMAT emergency responders',
      '24x7 armed perimeter watchtowers and canine patrol along plant boundaries',
    ],
    complianceRequirements: [
      'Factories Act 1948 safety and welfare regulations',
      'Petroleum and Explosives Safety Organization (PESO) compliance',
      'Contract Labour (R&A) Act 1970 registration and monthly returns',
      'State Industrial Disputes Act security protocols',
    ],
    caseStudy: {
      title: 'Plant Security & Fire Brigade for 100-Acre Chemical Manufacturing Unit',
      clientType: 'Multinational Chemical & Polymers Corporation',
      challenge: 'Securing hazardous processing units, multiple contractor workforces, and round-the-clock tanker movements.',
      solution: 'ACS deployed 55 industrial guards, 6 certified fire tenders/operators, and established computerized RFID gate logging.',
      result: 'Zero safety incidents, 100% regulatory audit compliance, and zero cargo shrinkage across 3 years.',
    },
    keywords: [
      'industrial security solutions India',
      'factory security guards',
      'manufacturing plant security agency',
      'chemical plant security services',
      'SEZ industrial security guard deployment',
    ],
  },
  {
    slug: 'government',
    name: 'Government, Secretariats & PSU Facilities',
    shortName: 'Government & PSU Security',
    tagline: 'GeM empanelled, PSARA compliant security for Central & State Government bodies.',
    description: 'Empanelled security services for Central & State Government secretariats, public sector undertakings, municipal bodies, and courts.',
    longDescription: 'ACS is a premier B2G vendor fully registered on GeM (Government e-Marketplace) and compliant with Central and State Government tender regulations. We provide verified, disciplined security personnel for ministries, collectorates, municipal corporations, public sector undertakings (PSUs), and judicial complexes.',
    icon: '🏛️',
    heroImage: '/images/about-us.jpg',
    relevantServices: ['security-guard', 'armed-guard', 'surveillance-cctv', 'fire-fighting', 'housekeeping'],
    keyChallenges: [
      'Massive public footfall, public grievance delegations, and protest management',
      'High-profile VIP movement and sensitive document security',
      'Strict adherence to Central Labour Sphere minimum wage circulars and EPFO mandates',
      'Zero-tolerance for regulatory non-compliance during CAG and vigilance audits',
    ],
    acsSolutions: [
      'GeM registered seller credentials with full statutory tax and labour compliance',
      'DGR (Directorate General Resettlement) and ex-servicemen security cadres',
      'Multi-tiered public screening checkpoints with DFMD, HHMD, and x-ray baggage scanners',
      'Audited monthly EPF ECR, ESIC challan, and bank wage disbursement transparency',
    ],
    complianceRequirements: [
      'Private Security Agencies (Regulation) Act 2005 (PSARA Form V)',
      'General Financial Rules (GFR) 2017 & GeM GTC tender norms',
      'Chief Labour Commissioner (Central) statutory wage gazette notifications',
      'ISO 9001:2015, ISO 14001:2015, and ISO 45001:2018 certifications',
    ],
    caseStudy: {
      title: 'Pan-State Security Manning for Public Sector Corporation Head Office',
      clientType: 'State Government Public Sector Undertaking',
      challenge: 'Managing public access across 7 regional branch complexes while maintaining 100% statutory PF/ESI transparency for state audit.',
      solution: 'ACS deployed 110 guards with bi-weekly supervisor inspections, unified digital payroll, and automated bank wage transfers.',
      result: 'Tender contract renewed for 3 consecutive terms with perfect CAG compliance scores.',
    },
    keywords: [
      'government security services India',
      'PSU security agency',
      'Central Government security guards',
      'State Government tender security contractor',
      'GeM security service provider',
    ],
  },
  {
    slug: 'defence-establishments',
    name: 'Defence Bases, Cantonments & Military Depots',
    shortName: 'Defence Establishments',
    tagline: 'Perimeter escort, military engineering services security, and ex-servicemen cadres.',
    description: 'Specialized security support for defence cantonments, air bases, military engineering stations, and veteran-led guarding operations.',
    longDescription: 'ACS deploys ex-servicemen (ESM) security guards and experienced supervisors for defence cantonments, Military Engineer Services (MES) depots, Air Force peripheral areas, and ordnance supply stations. Our personnel possess deep familiarity with military protocols, discipline, and security standing orders.',
    icon: '⭐',
    heroImage: '/images/training.jpg',
    relevantServices: ['armed-guard', 'security-guard', 'industrial-security', 'night-patrol', 'fire-fighting'],
    keyChallenges: [
      'Strict national security protocols and non-negotiable perimeter sanctity',
      'High-risk ammunition, fuel storage, and defense equipment depots',
      'Stringent personnel character and intelligence verification prerequisites',
      'Round-the-clock sentry vigilance in remote and challenging geographical terrains',
    ],
    acsSolutions: [
      'Over 60% ex-army, navy, and air force veteran workforce deployment',
      'Licensed armed guards with rigorous annual shooting range requalification',
      'Strict access badge logging and biometric verification at cantonment gates',
      'Joint perimeter patrols and mock threat drills with military station officers',
    ],
    complianceRequirements: [
      'Defence security clearance and IB / Local Police character verifications',
      'Arms Act 1959 valid firearm licenses and safe weapon custody protocols',
      'PSARA compliance across defence cantonment jurisdictions',
      'Statutory minimum wages per Central Sphere Defence / MES rates',
    ],
    caseStudy: {
      title: 'Auxiliary Guarding for Strategic Military Engineer Depot',
      clientType: 'Defence Infrastructure Establishment',
      challenge: 'Round-the-clock sentry protection of equipment yards spread over 80 acres with zero unauthorized perimeter breaches.',
      solution: 'ACS stationed 40 ex-servicemen guards with 24x7 watchtower manning, searchlights, and motorized perimeter patrol.',
      result: 'Flawless 5-year security record with formal commendations from Commanding Officers.',
    },
    keywords: [
      'defence establishment security India',
      'army cantonment security guards',
      'military depot security agency',
      'ex-servicemen security guards',
      'MES defence contractor security',
    ],
  },
  {
    slug: 'railways',
    name: 'Railways, Metro & Transit Infrastructure',
    shortName: 'Railway Security',
    tagline: 'Station crowd control, yard security, workshop protection, and goods shed watch.',
    description: 'Security services for railway workshops, goods yards, locomotive sheds, metro stations, and public passenger transit hubs.',
    longDescription: 'Railway networks and metro corridors are high-density public infrastructures requiring disciplined crowd management and asset guarding. ACS provides specialized transit security for railway workshops, locomotive repair sheds, goods loading yards, passenger concourses, and ticket gate access control.',
    icon: '🚆',
    heroImage: '/images/specialevent.jpg',
    relevantServices: ['security-guard', 'surveillance-cctv', 'event-security', 'industrial-security', 'fire-fighting'],
    keyChallenges: [
      'Massive passenger footfalls during peak commuting hours and festive rushes',
      'Theft of railway track fittings, signaling cables, brass fittings, and locomotive spares',
      'Trespassing on active railway tracks and unauthorized goods yard entry',
      'Emergency crowd stampede risks and unattended baggage security concerns',
    ],
    acsSolutions: [
      'Trained transit marshals managing passenger queuing at gates and escalators',
      'Goods yard sentry squads preventing scrap and consignment pilferage',
      'Handheld metal detector screening and luggage scanning operators',
      'Quick reaction teams coordinating directly with RPF (Railway Protection Force) and GRP',
    ],
    complianceRequirements: [
      'Indian Railways standard operating security guidelines',
      'Public Premises (Eviction of Unauthorized Occupants) Act adherence',
      'Central Labour Sphere railway worker minimum wage compliance',
      'Statutory EPF, ESIC, and workplace accident insurance coverage',
    ],
    caseStudy: {
      title: 'Yard & Workshop Security for Regional Railway Divisional Depot',
      clientType: 'Indian Railways Zonal Division',
      challenge: 'Securing high-value copper signaling cables, diesel locomotives, and spares against local scrap mafia intrusion.',
      solution: 'ACS deployed 32 trained guards with night searchlights, canine patrols, and dedicated gate inspection checkpoints.',
      result: 'Zero cable theft incidents recorded over a 24-month contract cycle.',
    },
    keywords: [
      'railway security services India',
      'metro station security guards',
      'railway workshop security agency',
      'goods yard security contractor',
      'passenger transit crowd control',
    ],
  },
  {
    slug: 'airports',
    name: 'Airports, Aviation Cargo & Transport Hubs',
    shortName: 'Airport Security',
    tagline: 'Landside terminal security, cargo escort, parking management, and access control.',
    description: 'Airport security support, aviation cargo escort, landside crowd control, vehicular screening, and terminal facility care.',
    longDescription: 'ACS provides auxiliary security and facility services for airport landside terminals, aviation cargo complexes, aircraft maintenance hangars, and passenger parking zones. Our personnel support airline operators, cargo forwarders, and airport concessionaires with strictly vetted security staff.',
    icon: '✈️',
    heroImage: '/images/guarding.jpg',
    relevantServices: ['security-guard', 'surveillance-cctv', 'executive-protection', 'housekeeping', 'mep-maintenance'],
    keyChallenges: [
      'Stringent BCAS (Bureau of Civil Aviation Security) background clearance mandates',
      'High-value bonded cargo transit and customs-bonded warehouse security',
      'Heavy vehicular congestion at departures, arrivals, and commercial taxi lanes',
      'Multi-tier access badge verification across airside and landside security boundaries',
    ],
    acsSolutions: [
      '100% BCAS cleared and police verified security personnel',
      'Bonded cargo container escort teams and seal verification checkers',
      'Traffic marshals streamlining airport departure ramps and commercial cab lanes',
      '24x7 control room operators coordinating with CISF airport command',
    ],
    complianceRequirements: [
      'Bureau of Civil Aviation Security (BCAS) AVSEC regulations',
      'Airports Authority of India (AAI) concessionaire security norms',
      'Contract Labour Act 1970 registration with Central Sphere licensing',
      'Mandatory EPF, ESIC, and aviation safety training certifications',
    ],
    caseStudy: {
      title: 'Cargo Terminal & Perimeter Security for International Air Cargo Hub',
      clientType: 'Air Cargo Logistics Operator',
      challenge: 'Securing bonded electronics and pharmaceutical consignments with strict turnaround and zero-pilferage SLAs.',
      solution: 'ACS stationed 24 vetted security guards with barcode seal verification and 24x7 CCTV dock monitoring.',
      result: 'Maintained 100% zero-tampering record across 50,000+ airborne cargo consignments.',
    },
    keywords: [
      'airport security services India',
      'aviation cargo security agency',
      'air cargo terminal security guards',
      'airport parking traffic marshals',
      'BCAS compliant auxiliary airport guards',
    ],
  },
  {
    slug: 'educational-institutions',
    name: 'Universities, Colleges & Educational Campuses',
    shortName: 'University & Campus Security',
    tagline: 'Student safety, hostel access control, visitor screening, and convocation events.',
    description: 'Campus security services for universities, engineering colleges, international schools, student hostels, and research campuses.',
    longDescription: 'Educational institutions require a protective, polite, and reassuring security presence. ACS deploys vetted campus security guards and female security wardens for universities, colleges, and schools. Our personnel manage campus main gates, monitor student hostels, prevent ragging or unauthorized intrusions, and ensure peaceful academic environments.',
    icon: '🎓',
    heroImage: '/images/training.jpg',
    relevantServices: ['security-guard', 'surveillance-cctv', 'event-security', 'housekeeping', 'horticulture'],
    keyChallenges: [
      'Unauthorized external visitors and trespassers entering student zones',
      'Safety and privacy of female students in residential hostels',
      'Large student crowds, university elections, and convocation ceremony events',
      'Traffic congestion and child safety during school bus arrival and dispersal hours',
    ],
    acsSolutions: [
      'Polite, background-verified security guards and trained female security wardens',
      'Visitor badge provisioning and parent ID verification at campus entry gates',
      'CCTV monitoring of campus boundaries, parking zones, and hostel entry doors',
      'Traffic marshals ensuring safe passage for school buses and pedestrians',
    ],
    complianceRequirements: [
      'POCSO guidelines and 100% police character verification for all school staff',
      'UGC / AICTE safety and security advisory guidelines for higher education campuses',
      'PSARA licensing and State Labour Department registration',
      'Statutory minimum wages with full EPF/ESIC and bonus remittances',
    ],
    caseStudy: {
      title: 'Integrated Campus Security for 35-Acre State University',
      clientType: 'Premier State University & Research Institute',
      challenge: 'Managing 6 vehicle gates, 4 student hostels, and preventing political clashes during campus student council elections.',
      solution: 'ACS deployed 36 guards, 4 female wardens, motorized night perimeter patrols, and established a central CCTV watch center.',
      result: 'Campus reported zero security incidents, zero trespassing, and smooth conduct of annual convocation with 5,000 attendees.',
    },
    keywords: [
      'university security services India',
      'college campus security agency',
      'school security guards',
      'student hostel female wardens',
      'educational institution security contractor',
    ],
  },
  {
    slug: 'malls',
    name: 'Retail Malls, Multiplexes & Shopping Centers',
    shortName: 'Retail & Mall Security',
    tagline: 'Loss prevention, DFMD bag screening, crowd control, and parking management.',
    description: 'Shopping mall security guards, customer greeting, DFMD metal detector screening, shoplifting prevention, and parking marshals.',
    longDescription: 'ACS provides high-visibility, polished retail security teams for shopping malls, hypermarkets, multiplexes, and retail fashion flagship stores. Our guards manage entrance metal detectors, screen visitor bags, prevent shoplifting, patrol escalators and food courts, and maintain order in multi-level parking basements.',
    icon: '🛍️',
    heroImage: '/images/specialevent.jpg',
    relevantServices: ['security-guard', 'event-security', 'surveillance-cctv', 'housekeeping', 'fire-fighting'],
    keyChallenges: [
      'Shoplifting, merchandise tagging tampering, and internal staff inventory theft',
      'Overwhelming crowds during weekend sales, holiday festivals, and film premieres',
      'Lost children, medical fainting incidents, and escalator slip-and-fall hazards',
      'Basement parking congestion, vehicle break-ins, and traffic jams at entry ramps',
    ],
    acsSolutions: [
      'Smartly uniformed greeting guards at mall main portals with DFMD and HHMD gear',
      'Plainclothes loss prevention officers patrolling retail aisles and fitting rooms',
      'First-aid certified mall marshals equipped with wireless walkie-talkies',
      'Boom barrier operators and parking marshals directing vehicle flow in basements',
    ],
    complianceRequirements: [
      'State Cinemas & Entertainment Establishments safety regulations',
      'National Building Code (NBC) mall fire and emergency evacuation compliance',
      'Shops and Establishments Act statutory compliance',
      '100% PSARA licensing and statutory PF/ESIC for all mall staff',
    ],
    caseStudy: {
      title: 'Security & Crowd Management for 450,000 Sq Ft Regional Shopping Mall',
      clientType: 'Leading Retail Mall Developer & Operator',
      challenge: 'Handling 35,000+ weekend footfalls with high risk of shoplifting and chaotic basement parking jams.',
      solution: 'ACS deployed 42 trained retail guards, 6 parking marshals, and established rapid-response lost-and-found protocols.',
      result: 'Shoplifting incidents reduced by 85%, and average vehicle parking turnaround dropped by 6 minutes.',
    },
    keywords: [
      'mall security services India',
      'retail security guards',
      'shopping center security agency',
      'multiplex crowd management security',
      'loss prevention guards retail stores',
    ],
  },
];

export function getIndustryBySlug(slug: string): ACSIndustry | undefined {
  return ACS_INDUSTRIES.find((i) => i.slug === slug);
}
