export interface ACSService {
  slug: string;
  name: string;
  shortName: string;
  category: 'security' | 'facility' | 'manpower' | 'horticulture';
  parentSlug?: string;
  description: string;
  longDescription: string;
  keywords: string[];
  schemaType: 'SecurityService' | 'ProfessionalService' | 'EmploymentAgency' | 'LandscapingService';
  icon: string;
  features: string[];
  clientTypes: string[];
  heroImage: string;
  metaTitleTemplate: string;
  metaDescTemplate: string;
  h1Template: string;
  h2Template: string;
}

export const ACS_SERVICES: ACSService[] = [
  // ─── Security (8) ─────────────────────────────────────────────────────────
  {
    slug: 'security-guard',
    name: 'Security Guard Services',
    shortName: 'Security Guards',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Professional PSARA-licensed security guard deployment for corporate, industrial, and government establishments.',
    longDescription: 'Advance Corporate Services provides battle-tested, PSARA-licensed security guards for offices, factories, hospitals, banks, and government buildings across India. All personnel are background-verified, uniformed, trained in first aid, fire-fighting, and emergency response.',
    keywords: [
      'PSARA licensed security services in [City]',
      'corporate security guard agency [City]',
      'security guard company [City]',
      'professional security guards [City]',
      'security agency for offices [City]',
      'B2B security services India',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F46E}',
    features: [
      'PSARA licensed & government compliant',
      'Armed & unarmed guard options',
      'Background-verified personnel',
      '24x7 deployment capability',
      'Uniformed & trained guards',
      'Supervisory oversight included',
      'Statutory PF/ESIC compliance',
    ],
    clientTypes: [
      'Corporate Offices',
      'Banks',
      'Hospitals',
      'Government Buildings',
      'Industrial Plants',
      'Malls',
      'Educational Institutions',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'PSARA Licensed Security Guard Services in [City] | ACS',
    metaDescTemplate: 'Hire professional PSARA-licensed security guards in [City]. ACS provides background-verified, ISO 9001:2015 certified armed & unarmed security for corporate and industrial sectors. Get free quote.',
    h1Template: 'PSARA Licensed Security Guard Services in [City]',
    h2Template: '24x7 Armed & Unarmed Guard Deployment for [City] Businesses',
  },
  {
    slug: 'armed-guard',
    name: 'Armed Guard Services',
    shortName: 'Armed Guards',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Licensed armed security personnel for banks, jewelry stores, high-value asset protection and cash-in-transit.',
    longDescription: 'ACS deploys PSARA-certified armed security guards equipped for high-risk environments. Our armed guards protect bank branches, ATMs, cash-in-transit vans, jewelry establishments, and government vaults with full statutory compliance.',
    keywords: [
      'armed security guards for banks in [City]',
      'armed guard services [City]',
      'cash-in-transit security [City]',
      'PSARA armed guards India',
      'bank security agency [City]',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F6E1}\uFE0F',
    features: [
      'Licensed firearms training',
      'Cash-in-transit protection',
      'Bank & ATM security',
      'Jewelry store protection',
      'Government vault security',
      'Ex-servicemen personnel',
      'Full PSARA compliance',
    ],
    clientTypes: [
      'Banks & NBFCs',
      'Jewelry Stores',
      'Cash Management Companies',
      'Government Vaults',
      'Bullion Dealers',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Armed Security Guard Services in [City] | PSARA Licensed - ACS',
    metaDescTemplate: 'Hire licensed armed security guards in [City] for bank, ATM, and high-value asset protection. ACS provides PSARA-compliant armed guard services across [City]. Contact for quotation.',
    h1Template: 'Licensed Armed Security Guard Services in [City]',
    h2Template: 'High-Value Asset & Bank Protection for [City] Businesses',
  },
  {
    slug: 'surveillance-cctv',
    name: 'Surveillance & CCTV Monitoring',
    shortName: 'CCTV Surveillance',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Round-the-clock CCTV surveillance, control room operations, and integrated electronic security monitoring.',
    longDescription: 'ACS operates dedicated 24x7 control rooms for CCTV monitoring, access control management, and integrated electronic security systems. Our surveillance operators are trained to detect anomalies and trigger rapid response protocols.',
    keywords: [
      'CCTV surveillance services [City]',
      'electronic security monitoring [City]',
      'access control system [City]',
      'control room security services India',
      'integrated security systems corporate offices',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F4F9}',
    features: [
      '24x7 control room operations',
      'Multi-channel CCTV monitoring',
      'Access control management',
      'Intrusion detection systems',
      'Incident reporting & escalation',
      'Remote monitoring capability',
      'Fire alarm integration',
    ],
    clientTypes: [
      'Corporate Campuses',
      'IT Parks',
      'Hospitals',
      'Warehouses',
      'Manufacturing Plants',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'CCTV Surveillance & Security Monitoring in [City] | ACS',
    metaDescTemplate: 'Professional CCTV surveillance and 24x7 control room security monitoring in [City]. ACS provides integrated electronic security systems for corporate and industrial premises.',
    h1Template: 'Professional CCTV Surveillance & Monitoring Services in [City]',
    h2Template: '24x7 Control Room Operations for [City] Corporate Premises',
  },
  {
    slug: 'night-patrol',
    name: 'Night Patrolling Services',
    shortName: 'Night Patrolling',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Trained security personnel for nighttime perimeter patrol, guard rounds, and after-hours premises security.',
    longDescription: 'ACS provides disciplined, trained security guards for night patrolling operations. Our guards conduct systematic rounds, use GPS-tracked patrol routes, and submit digital patrol reports for corporate and industrial premises.',
    keywords: [
      'night patrolling security services [City]',
      'after hours security [City]',
      'perimeter security guards [City]',
      'industrial night security [City]',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F319}',
    features: [
      'GPS-tracked patrol routes',
      'Digital patrol reports',
      'Perimeter security checks',
      'Intrusion detection',
      'Emergency response protocol',
      'Dog squad available',
      'Regular supervisory audits',
    ],
    clientTypes: [
      'Industrial Plants',
      'Warehouses',
      'Construction Sites',
      'Gated Communities',
      'Corporate Campuses',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Night Patrolling Security Services in [City] | ACS',
    metaDescTemplate: 'Professional night patrolling and after-hours security services in [City]. ACS guards conduct GPS-tracked patrol rounds for industrial and corporate premises security.',
    h1Template: 'Reliable Night Patrolling Security Services in [City]',
    h2Template: 'GPS-Tracked After-Hours Security Patrol for [City] Premises',
  },
  {
    slug: 'executive-protection',
    name: 'Executive & VIP Protection',
    shortName: 'VIP Protection',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Close protection and personal security services for corporate executives, dignitaries, and high-net-worth individuals.',
    longDescription: 'ACS provides discreet, professional close protection services for corporate executives, VIPs, and dignitaries. Our protection officers are ex-servicemen trained in threat assessment, route planning, and emergency evacuation protocols.',
    keywords: [
      'executive protection services [City]',
      'VIP security services India',
      'personal security officer [City]',
      'close protection agency India',
      'corporate executive security',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F574}\uFE0F',
    features: [
      'Ex-servicemen close protection officers',
      'Threat assessment & route planning',
      'Advance reconnaissance',
      'Event security detail',
      'Residential security',
      'Travel security management',
      'Discreet & professional service',
    ],
    clientTypes: [
      'Corporate Executives',
      'Diplomats',
      'High Net Worth Individuals',
      'Film & Entertainment',
      'Political Figures',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Executive & VIP Protection Services in [City] | ACS',
    metaDescTemplate: 'Professional executive protection and VIP security services in [City]. ACS provides ex-servicemen close protection officers for corporate executives and dignitaries.',
    h1Template: 'Executive & VIP Close Protection Services in [City]',
    h2Template: 'Discreet Personal Security Detail for [City] Executives & Dignitaries',
  },
  {
    slug: 'fire-fighting',
    name: 'Fire Fighting & Safety Services',
    shortName: 'Fire Safety',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Trained fire fighting teams, fire safety equipment management, mock drills, and emergency response planning.',
    longDescription: 'ACS provides dedicated fire safety personnel trained in firefighting, fire extinguisher maintenance, evacuation drills, and compliance with National Building Code fire safety standards. We deploy trained fire safety teams at factories, hospitals, and commercial buildings.',
    keywords: [
      'fire fighting services [City]',
      'fire safety personnel [City]',
      'industrial fire safety team [City]',
      'fire drill services India',
      'fire safety compliance [City]',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F692}',
    features: [
      'Trained fire fighting personnel',
      'Fire extinguisher maintenance',
      'Evacuation drill management',
      'National Building Code compliance',
      'Fire hydrant system upkeep',
      'Emergency response team',
      'Monthly safety audits',
    ],
    clientTypes: [
      'Factories',
      'Hospitals',
      'Hotels',
      'Commercial Buildings',
      'Chemical Plants',
      'Government Offices',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Fire Fighting & Safety Services in [City] | ACS',
    metaDescTemplate: 'Professional fire safety teams and firefighting services in [City]. ACS provides trained fire safety personnel, evacuation drills, and NBC compliance for industrial and commercial premises.',
    h1Template: 'Professional Fire Fighting & Safety Services in [City]',
    h2Template: 'Trained Fire Safety Teams & Emergency Response for [City] Industries',
  },
  {
    slug: 'event-security',
    name: 'Event Security Services',
    shortName: 'Event Security',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Crowd management, access control, and event-specific security for corporate events, exhibitions, and public gatherings.',
    longDescription: 'ACS deploys skilled event security personnel for corporate conferences, exhibitions, trade fairs, sports events, and public gatherings. Our event security teams manage crowd control, VIP access, perimeter security, and emergency response coordination.',
    keywords: [
      'event security services [City]',
      'event security management company',
      'corporate event security [City]',
      'exhibition security agency [City]',
      'crowd management security India',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F3AA}',
    features: [
      'Crowd management expertise',
      'VIP access control',
      'Perimeter security',
      'Emergency response coordination',
      'Metal detector screening',
      'CCTV monitoring during events',
      'Coordination with local police',
    ],
    clientTypes: [
      'Corporate Event Organizers',
      'Exhibition Centers',
      'Sports Venues',
      'Hotels',
      'Government Events',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Event Security Services in [City] | Crowd Management - ACS',
    metaDescTemplate: 'Professional event security and crowd management services in [City]. ACS provides trained event security teams for corporate events, exhibitions, and public gatherings.',
    h1Template: 'Professional Event Security & Crowd Management in [City]',
    h2Template: 'Trusted Event Security Teams for Corporate & Public Events in [City]',
  },
  {
    slug: 'industrial-security',
    name: 'Industrial Security Services',
    shortName: 'Industrial Security',
    category: 'security',
    parentSlug: 'security-safety',
    description: 'Specialized security for factories, power plants, oil & gas facilities, and other industrial establishments.',
    longDescription: 'ACS provides specialized industrial security services for manufacturing plants, power stations, oil refineries, chemical plants, and logistics warehouses. Our industrial security guards are trained in hazardous material awareness, plant safety protocols, and access control for restricted zones.',
    keywords: [
      'industrial security solutions near [City]',
      'factory security services [City]',
      'plant security agency [City]',
      'warehouse security guards [City]',
      'manufacturing security India',
    ],
    schemaType: 'SecurityService',
    icon: '\u{1F3ED}',
    features: [
      'Factory & plant security',
      'Hazmat awareness training',
      'Restricted zone access control',
      'Vehicle & goods screening',
      'Canine/dog squad services',
      'Power plant security',
      'Oil & gas facility security',
    ],
    clientTypes: [
      'Manufacturing Plants',
      'Power Stations',
      'Oil Refineries',
      'Chemical Plants',
      'Warehouses',
      'Steel Plants',
      'Port & Logistics Hubs',
    ],
    heroImage: '/images/security-service-slider.jpg',
    metaTitleTemplate: 'Industrial Security Services in [City] | Factory & Plant Security - ACS',
    metaDescTemplate: 'Specialized industrial security services in [City] for factories, power plants, and warehouses. ACS provides PSARA-licensed industrial security guards with hazmat training.',
    h1Template: 'Specialized Industrial & Factory Security Services in [City]',
    h2Template: 'PSARA Licensed Plant & Warehouse Security Guards in [City]',
  },
  // ─── Facility Management (5) ────────────────────────────────────────────────
  {
    slug: 'housekeeping',
    name: 'Corporate Housekeeping Services',
    shortName: 'Housekeeping',
    category: 'facility',
    parentSlug: 'facility-management',
    description: 'Professional corporate housekeeping and office cleaning services for offices, hospitals, hotels, and institutions.',
    longDescription: 'ACS provides trained, uniformed housekeeping staff for daily office cleaning, sanitation, and maintenance. Our housekeeping teams follow ISO-certified SOPs for surface disinfection, washroom maintenance, waste management, and common area upkeep.',
    keywords: [
      'corporate housekeeping services in [City]',
      'office cleaning services [City]',
      'professional housekeeping agency [City]',
      'facility management housekeeping [City]',
      'commercial cleaning companies [City]',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F9F9}',
    features: [
      'ISO-certified cleaning SOPs',
      'Trained & uniformed staff',
      'Daily & periodic deep cleaning',
      'Washroom sanitation',
      'Waste management',
      'Common area maintenance',
      'PF/ESIC compliant payroll',
    ],
    clientTypes: [
      'Corporate Offices',
      'Hospitals',
      'Hotels',
      'IT Parks',
      'Educational Institutions',
      'Malls',
    ],
    heroImage: '/images/facility-management-slider-new.jpg',
    metaTitleTemplate: 'Corporate Housekeeping Services in [City] | ACS Facility Management',
    metaDescTemplate: 'Professional corporate housekeeping and office cleaning in [City]. ACS provides ISO-certified, trained housekeeping staff for offices, hospitals, and institutions. Get free quote.',
    h1Template: 'Professional Corporate Housekeeping Services in [City]',
    h2Template: 'ISO-Certified Office Cleaning & Sanitation Staff for [City] Businesses',
  },
  {
    slug: 'janitorial',
    name: 'Janitorial & Deep Cleaning Services',
    shortName: 'Janitorial',
    category: 'facility',
    parentSlug: 'facility-management',
    description: 'Deep cleaning, floor care, sanitation, and specialized janitorial services for commercial establishments.',
    longDescription: 'ACS provides comprehensive janitorial services including deep cleaning, floor polishing, high-pressure washing, drain cleaning, glass cleaning, and periodic sanitization campaigns for commercial premises, hospitals, and industrial facilities.',
    keywords: [
      'janitorial services [City]',
      'commercial deep cleaning [City]',
      'floor cleaning services [City]',
      'building sanitation services [City]',
      'soft facility management services',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F9FD}',
    features: [
      'Deep cleaning operations',
      'Floor polishing & scrubbing',
      'High-pressure washing',
      'Drain & pipeline cleaning',
      'Post-construction cleaning',
      'Periodic sanitization',
      'Specialized equipment & chemicals',
    ],
    clientTypes: [
      'Hospitals',
      'Hotels',
      'Shopping Malls',
      'Corporate Offices',
      'Food Processing Units',
    ],
    heroImage: '/images/facility-management-slider-new.jpg',
    metaTitleTemplate: 'Janitorial & Deep Cleaning Services in [City] | ACS',
    metaDescTemplate: 'Professional janitorial and deep cleaning services in [City]. ACS provides commercial floor cleaning, sanitization, and building maintenance for offices and hospitals.',
    h1Template: 'Professional Janitorial & Deep Cleaning Services in [City]',
    h2Template: 'Commercial Floor Care & Sanitization for [City] Establishments',
  },
  {
    slug: 'pest-control',
    name: 'Commercial Pest Control Services',
    shortName: 'Pest Control',
    category: 'facility',
    parentSlug: 'facility-management',
    description: 'Integrated pest management for commercial premises including offices, warehouses, hotels, and food processing units.',
    longDescription: 'ACS provides integrated pest management (IPM) services for commercial and industrial premises. Our certified pest control teams handle rodent control, cockroach treatment, termite management, mosquito fogging, and all other pest-related issues with WHO-approved chemicals.',
    keywords: [
      'commercial pest control [City]',
      'integrated pest management [City]',
      'office pest control services [City]',
      'industrial pest control India',
      'warehouse pest management [City]',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F41B}',
    features: [
      'Integrated pest management (IPM)',
      'Rodent control',
      'Cockroach & ant treatment',
      'Termite management',
      'Mosquito fogging',
      'WHO-approved chemicals',
      'AMC (Annual Maintenance Contract) available',
    ],
    clientTypes: [
      'Offices',
      'Warehouses',
      'Hotels',
      'Restaurants',
      'Food Processing Units',
      'Hospitals',
    ],
    heroImage: '/images/facility-management-slider-new.jpg',
    metaTitleTemplate: 'Commercial Pest Control Services in [City] | Integrated Pest Management - ACS',
    metaDescTemplate: 'Professional commercial pest control and integrated pest management in [City]. ACS provides certified pest control for offices, warehouses, and food processing units.',
    h1Template: 'Commercial Pest Control & Integrated Pest Management in [City]',
    h2Template: 'Certified Pest Management Services for [City] Businesses & Industries',
  },
  {
    slug: 'facade-cleaning',
    name: 'Facade & Glass Cleaning Services',
    shortName: 'Facade Cleaning',
    category: 'facility',
    parentSlug: 'facility-management',
    description: 'Professional exterior facade cleaning, glass curtain wall cleaning, and rope access cleaning for commercial buildings.',
    longDescription: 'ACS provides professional facade cleaning services using rope access techniques, gondola systems, and water-fed pole systems for high-rise commercial buildings. Our trained cleaning teams safely restore the appearance of glass facades, cladding, and building exteriors.',
    keywords: [
      'office facade cleaning services [City]',
      'glass cleaning services [City]',
      'building exterior cleaning [City]',
      'rope access cleaning [City]',
      'curtain wall cleaning India',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F3E2}',
    features: [
      'Rope access & gondola systems',
      'High-rise facade cleaning',
      'Glass curtain wall cleaning',
      'Cladding cleaning & restoration',
      'Water-fed pole systems',
      'Safety-certified technicians',
      'WFPCS & IRATA trained staff',
    ],
    clientTypes: [
      'High-Rise Office Buildings',
      'IT Parks',
      'Hotels',
      'Malls',
      'Commercial Towers',
    ],
    heroImage: '/images/facility-management-slider-new.jpg',
    metaTitleTemplate: 'Facade & Glass Cleaning Services in [City] | High-Rise Cleaning - ACS',
    metaDescTemplate: 'Professional facade and glass curtain wall cleaning in [City]. ACS provides rope access and gondola-based exterior cleaning for high-rise commercial buildings.',
    h1Template: 'Professional Facade & Glass Cleaning Services in [City]',
    h2Template: 'High-Rise Exterior & Curtain Wall Cleaning for [City] Buildings',
  },
  {
    slug: 'mep-maintenance',
    name: 'MEP Maintenance Services',
    shortName: 'MEP Maintenance',
    category: 'facility',
    parentSlug: 'facility-management',
    description: 'Comprehensive Mechanical, Electrical & Plumbing (MEP) maintenance for commercial buildings and industrial facilities.',
    longDescription: 'ACS provides integrated MEP (Mechanical, Electrical, Plumbing) maintenance services covering HVAC maintenance, electrical panel upkeep, plumbing repairs, generator maintenance, fire suppression system checks, and preventive maintenance programs for commercial buildings.',
    keywords: [
      'MEP maintenance services [City]',
      'building maintenance services for IT parks',
      'HVAC maintenance [City]',
      'electrical maintenance services [City]',
      'hard facility management services',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u2699\uFE0F',
    features: [
      'HVAC maintenance & AMC',
      'Electrical panel maintenance',
      'Plumbing & drainage repairs',
      'Generator & DG set maintenance',
      'Fire suppression system checks',
      'Preventive maintenance schedules',
      'Energy audit services',
    ],
    clientTypes: [
      'IT Parks',
      'Corporate Offices',
      'Hospitals',
      'Hotels',
      'Industrial Plants',
      'Data Centers',
    ],
    heroImage: '/images/facility-management-slider-new.jpg',
    metaTitleTemplate: 'MEP Maintenance Services in [City] | Mechanical Electrical Plumbing - ACS',
    metaDescTemplate: 'Professional MEP (Mechanical, Electrical & Plumbing) maintenance in [City]. ACS provides integrated hard facility management including HVAC, electrical, and plumbing services.',
    h1Template: 'MEP (Mechanical, Electrical & Plumbing) Maintenance in [City]',
    h2Template: 'Integrated Hard Facility Management Services for [City] Buildings',
  },
  // ─── Manpower (3) ───────────────────────────────────────────────────────────
  {
    slug: 'manpower-outsourcing',
    name: 'Manpower Outsourcing Services',
    shortName: 'Manpower Outsourcing',
    category: 'manpower',
    parentSlug: 'placement-services',
    description: 'Contract labour supply and manpower outsourcing for factories, warehouses, and industrial establishments.',
    longDescription: 'ACS provides skilled, semi-skilled, and unskilled contract manpower for industrial, logistics, and commercial operations. We handle all statutory compliances including PF, ESIC, minimum wages, and labour law documentation for all outsourced staff.',
    keywords: [
      'contract labor outsourcing in [City]',
      'skilled manpower supply agency [City]',
      'industrial manpower outsourcing India',
      'factory worker provider in [City]',
      'temporary staffing for manufacturing',
      'blue-collar workforce provider',
    ],
    schemaType: 'EmploymentAgency',
    icon: '\u{1F477}',
    features: [
      'Skilled & unskilled manpower supply',
      'Full statutory compliance (PF, ESIC)',
      'Minimum Wage Act adherence',
      'Labour contract management',
      'On-site supervisory staff',
      'Background-verified workers',
      'Flexible deployment models',
    ],
    clientTypes: [
      'Factories',
      'Warehouses',
      'Construction Companies',
      'Logistics Firms',
      'Infrastructure Projects',
    ],
    heroImage: '/images/placement-service-slider.jpg',
    metaTitleTemplate: 'Manpower Outsourcing Services in [City] | Contract Labour Supply - ACS',
    metaDescTemplate: 'Reliable manpower outsourcing and contract labour supply in [City]. ACS provides skilled, semi-skilled, and unskilled workforce with full PF, ESIC, and labour law compliance.',
    h1Template: 'Trusted Manpower Outsourcing Agency in [City]',
    h2Template: 'Contract Labour & Skilled Workforce Solutions in [City]',
  },
  {
    slug: 'placement-services',
    name: 'Permanent & Temporary Placement Services',
    shortName: 'Placement Services',
    category: 'manpower',
    parentSlug: 'placement-services',
    description: 'Executive recruitment, temporary staffing, and permanent placement services for corporate and industrial sectors.',
    longDescription: 'ACS connects qualified candidates with corporates, industries, and government organizations across India. Our placement services cover executive search, mid-level recruitment, and bulk staffing for blue-collar and white-collar roles with end-to-end HR support.',
    keywords: [
      'recruitment agencies in [City]',
      'placement services [City]',
      'staffing agency [City]',
      'temporary staffing solutions India',
      'HR outsourcing companies in India',
    ],
    schemaType: 'EmploymentAgency',
    icon: '\u{1F91D}',
    features: [
      'Executive & mid-level search',
      'Bulk staffing solutions',
      'Resume screening & shortlisting',
      'Interview coordination',
      'Offer letter & onboarding support',
      'Background verification',
      'Permanent & contract placements',
    ],
    clientTypes: [
      'Corporates',
      'Hospitals',
      'IT Companies',
      'Manufacturing Firms',
      'Government PSUs',
    ],
    heroImage: '/images/placement-service-slider.jpg',
    metaTitleTemplate: 'Placement & Staffing Services in [City] | Recruitment Agency - ACS',
    metaDescTemplate: 'Professional placement and staffing services in [City]. ACS provides executive recruitment, temporary staffing, and permanent placement for corporate and industrial sectors.',
    h1Template: 'Professional Placement & Staffing Services in [City]',
    h2Template: 'Executive Recruitment & Bulk Staffing Solutions in [City]',
  },
  {
    slug: 'payroll-management',
    name: 'Payroll & Compliance Management',
    shortName: 'Payroll Management',
    category: 'manpower',
    parentSlug: 'placement-services',
    description: 'End-to-end payroll processing, statutory compliance, and HR administration for outsourced workforce.',
    longDescription: 'ACS manages complete payroll processing and statutory compliance for outsourced staff including PF deposits, ESIC contributions, professional tax, bonus calculations, and leave management — ensuring zero legal exposure for client organizations.',
    keywords: [
      'payroll outsourcing services India',
      'payroll management services [City]',
      'PF ESIC compliance services [City]',
      'HR outsourcing companies in India',
      'statutory compliance services India',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F4CA}',
    features: [
      'Monthly payroll processing',
      'PF & ESIC deposit management',
      'Professional tax filing',
      'Bonus & leave management',
      'Form 16 generation',
      'Labour law compliance',
      'Minimum Wage Act adherence',
    ],
    clientTypes: [
      'All Industries',
      'SMEs',
      'Large Corporates',
      'Manufacturing Companies',
      'NGOs',
    ],
    heroImage: '/images/placement-service-slider.jpg',
    metaTitleTemplate: 'Payroll & Compliance Management Services in [City] | ACS',
    metaDescTemplate: 'Professional payroll processing and statutory compliance management in [City]. ACS handles PF, ESIC, professional tax, and all HR compliance for outsourced workforce.',
    h1Template: 'Payroll & Statutory Compliance Management in [City]',
    h2Template: 'PF, ESIC & Labour Law Compliance Services for [City] Businesses',
  },
  // ─── Horticulture (1) ───────────────────────────────────────────────────────
  {
    slug: 'horticulture',
    name: 'Horticulture & Landscaping Services',
    shortName: 'Horticulture',
    category: 'horticulture',
    description: 'Professional landscaping, garden design, grounds keeping, and lawn maintenance for corporate campuses and institutions.',
    longDescription: 'ACS provides expert horticulture services including garden design, lawn maintenance, tree plantation, indoor plant care, and grounds keeping for corporate campuses, government offices, hospitals, and educational institutions.',
    keywords: [
      'horticulture services [City]',
      'landscaping services [City]',
      'corporate garden maintenance [City]',
      'grounds keeping services India',
      'lawn maintenance services [City]',
    ],
    schemaType: 'ProfessionalService',
    icon: '\u{1F33F}',
    features: [
      'Garden design & landscaping',
      'Lawn maintenance & mowing',
      'Tree plantation & pruning',
      'Indoor plant care',
      'Irrigation system maintenance',
      'Seasonal floral arrangements',
      'Vermicomposting & organic care',
    ],
    clientTypes: [
      'Corporate Campuses',
      'Government Offices',
      'Hospitals',
      'Hotels',
      'Educational Institutions',
      'Residential Complexes',
    ],
    heroImage: '/images/horticulture-slider.jpg',
    metaTitleTemplate: 'Horticulture & Landscaping Services in [City] | ACS',
    metaDescTemplate: 'Professional horticulture and landscaping services in [City]. ACS provides garden design, lawn maintenance, and grounds keeping for corporate campuses and institutions.',
    h1Template: 'Professional Horticulture & Landscaping Services in [City]',
    h2Template: 'Expert Garden Design & Grounds Keeping for [City] Corporate Campuses',
  },
];

export const ACS_SERVICE_CATEGORIES = [
  {
    slug: 'security-safety',
    name: 'Security & Safety Services',
    icon: '\u{1F6E1}\uFE0F',
    description: 'PSARA-licensed armed & unarmed security guard services, CCTV surveillance, night patrolling, and fire fighting.',
  },
  {
    slug: 'facility-management',
    name: 'Facility Management',
    icon: '\u{1F3E2}',
    description: 'Integrated facility management including corporate housekeeping, MEP maintenance, pest control, and facade cleaning.',
  },
  {
    slug: 'placement-services',
    name: 'Manpower & Placement',
    icon: '\u{1F477}',
    description: 'Contract labour outsourcing, placement services, and payroll compliance management across India.',
  },
  {
    slug: 'horticulture',
    name: 'Horticulture & Landscaping',
    icon: '\u{1F33F}',
    description: 'Professional landscaping, garden design, and grounds keeping for corporate campuses.',
  },
] as const;

export function getServiceBySlug(slug: string): ACSService | undefined {
  return ACS_SERVICES.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: ACSService['category']): ACSService[] {
  return ACS_SERVICES.filter((s) => s.category === category);
}

export function generateServiceMeta(
  service: ACSService,
  cityName?: string,
): { title: string; description: string } {
  if (!cityName) {
    return {
      title: `${service.name} | Advance Corporate Services`,
      description: service.description,
    };
  }
  return {
    title: service.metaTitleTemplate.replace(/\[City\]/g, cityName),
    description: service.metaDescTemplate.replace(/\[City\]/g, cityName),
  };
}
